language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4"
  - "5"
  - "6"
env: 
  - WEBPACK=webpack
  - WEBPACK=webpack@beta
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm install $WEBPACK --ignore-scripts || true
script:
  - npm test